eureka:
  instance:
          prefer-ip-address: true
          instance-id: ${spring.cloud.client.ip-address}:${server.port}
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
  application:
    name: order
  jpa:
    show-sql: true
  rabbitmq:
    host: 192.168.40.128
    port: 5672
    username: guest
    password: guest  
env:
 test
girl:
  name: lili
  age: 20
